/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetTramyRouteImport } from './routes/widget-tramy'
import { Route as PoptavkaPergolyRouteImport } from './routes/poptavka-pergoly'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as DopravaRouteImport } from './routes/doprava'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdministraceRouteImport } from './routes/administrace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIdRouteImport } from './routes/category.$id'

const WidgetTramyRoute = WidgetTramyRouteImport.update({
  id: '/widget-tramy',
  path: '/widget-tramy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoptavkaPergolyRoute = PoptavkaPergolyRouteImport.update({
  id: '/poptavka-pergoly',
  path: '/poptavka-pergoly',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const DopravaRoute = DopravaRouteImport.update({
  id: '/doprava',
  path: '/doprava',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministraceRoute = AdministraceRouteImport.update({
  id: '/administrace',
  path: '/administrace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrace': typeof AdministraceRoute
  '/checkout': typeof CheckoutRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
  '/poptavka-pergoly': typeof PoptavkaPergolyRoute
  '/widget-tramy': typeof WidgetTramyRoute
  '/category/$id': typeof CategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrace': typeof AdministraceRoute
  '/checkout': typeof CheckoutRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
  '/poptavka-pergoly': typeof PoptavkaPergolyRoute
  '/widget-tramy': typeof WidgetTramyRoute
  '/category/$id': typeof CategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrace': typeof AdministraceRoute
  '/checkout': typeof CheckoutRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
  '/poptavka-pergoly': typeof PoptavkaPergolyRoute
  '/widget-tramy': typeof WidgetTramyRoute
  '/category/$id': typeof CategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrace'
    | '/checkout'
    | '/doprava'
    | '/o-nas'
    | '/poptavka-pergoly'
    | '/widget-tramy'
    | '/category/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrace'
    | '/checkout'
    | '/doprava'
    | '/o-nas'
    | '/poptavka-pergoly'
    | '/widget-tramy'
    | '/category/$id'
  id:
    | '__root__'
    | '/'
    | '/administrace'
    | '/checkout'
    | '/doprava'
    | '/o-nas'
    | '/poptavka-pergoly'
    | '/widget-tramy'
    | '/category/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministraceRoute: typeof AdministraceRoute
  CheckoutRoute: typeof CheckoutRoute
  DopravaRoute: typeof DopravaRoute
  ONasRoute: typeof ONasRoute
  PoptavkaPergolyRoute: typeof PoptavkaPergolyRoute
  WidgetTramyRoute: typeof WidgetTramyRoute
  CategoryIdRoute: typeof CategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget-tramy': {
      id: '/widget-tramy'
      path: '/widget-tramy'
      fullPath: '/widget-tramy'
      preLoaderRoute: typeof WidgetTramyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poptavka-pergoly': {
      id: '/poptavka-pergoly'
      path: '/poptavka-pergoly'
      fullPath: '/poptavka-pergoly'
      preLoaderRoute: typeof PoptavkaPergolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doprava': {
      id: '/doprava'
      path: '/doprava'
      fullPath: '/doprava'
      preLoaderRoute: typeof DopravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrace': {
      id: '/administrace'
      path: '/administrace'
      fullPath: '/administrace'
      preLoaderRoute: typeof AdministraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministraceRoute: AdministraceRoute,
  CheckoutRoute: CheckoutRoute,
  DopravaRoute: DopravaRoute,
  ONasRoute: ONasRoute,
  PoptavkaPergolyRoute: PoptavkaPergolyRoute,
  WidgetTramyRoute: WidgetTramyRoute,
  CategoryIdRoute: CategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
