/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as DopravaRouteImport } from './routes/doprava'
import { Route as IndexRouteImport } from './routes/index'

const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const DopravaRoute = DopravaRouteImport.update({
  id: '/doprava',
  path: '/doprava',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doprava': typeof DopravaRoute
  '/o-nas': typeof ONasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doprava' | '/o-nas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doprava' | '/o-nas'
  id: '__root__' | '/' | '/doprava' | '/o-nas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DopravaRoute: typeof DopravaRoute
  ONasRoute: typeof ONasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doprava': {
      id: '/doprava'
      path: '/doprava'
      fullPath: '/doprava'
      preLoaderRoute: typeof DopravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DopravaRoute: DopravaRoute,
  ONasRoute: ONasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
